driver:
  name: ec2
  aws_access_key: ""
  aws_secret_key: ""
  region: eu-west-1
  instance_type: t2.micro
  require_chef_omnibus: true
  associate_public_ip: true

provisioner:
  name: chef_zero
  log_level: info
  chef_license: accept
  product_name: chef
  product_version: 14.12.3
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
  chef_license: accept-no-persist

platforms:
  - name: ubuntu-18.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[uber::default]
    verifier:
      inspec_tests:
        - test/integration/default
      chef_license: accept-no-persist
    attributes:
