driver_config:
  name: ec2
  region: eu-west-1
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  require_chef_omnibus: true
  instance_type: t2.micro
  associate_public_ip: true
  chef_license: accept-no-persist

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[uber::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
